name: sonot_app
description: "Sonot, the chat app. Made by ThatMaxwell."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-400.ttf
          weight: 400
        - asset: assets/fonts/InterTight-500.ttf
          weight: 500
        - asset: assets/fonts/InterTight-600.ttf
          weight: 600
        - asset: assets/fonts/InterTight-700.ttf
          weight: 700
        - asset: assets/fonts/InterTight-800.ttf
          weight: 800
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif-400.ttf
        - asset: assets/fonts/InstrumentSerif-400-italic.ttf
          style: italic
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-400.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-500.ttf
          weight: 500
